package org.example.department.enums;

public enum State {
    ABIA, ANAMBRA, EDO, RIVERS, CROSS_RIVERS, AKWA_IBOM, EKITI,
    LAGOS, DELTA, ABUJA, ENUGU, ADAMAWA, ANANBRA,
    PLATEAU, OYO, OSUN, ONDO, KANO, KADUNA,
    TARABA, KWARA, SOKOTO, JIGAWA, ZAMFARA, BORNO,
    BAYELSA, IMO, EBONYI, KEBBI, KATSINA, BENUE,
    BAUCHI, KOGI, YOBE, NIGER, GOMBE, NASARAWA,
}
